agent {
  data_dir = "/var/lib/spire/data"
  log_level = "INFO"
  server_address = "spire.aura.local"
  server_port = 8443
  socket_path = "/run/spire/sockets/agent.sock"
  trust_bundle_path = "/etc/spire/bundle.crt"
  trust_domain = "aura.local"
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {}
  }
  KeyManager "memory" {
    plugin_data {}
  }
  WorkloadAttestor "unix" {
    plugin_data {}
  }
}
